# Generated by Django 5.2.13 on 2026-04-12 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='наименование')),
                ('sku', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='SKU')),
                ('unit', models.CharField(max_length=32, verbose_name='ед. изм.')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='закупочная цена')),
                ('current_stock', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='текущий остаток')),
                ('min_stock', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='минимальный запас')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='SKLAD.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=64, unique=True, verbose_name='номер документа')),
                ('receipt_date', models.DateField(verbose_name='дата поступления')),
                ('supplier_name', models.CharField(max_length=200, verbose_name='поставщик')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('posted', 'Проведён'), ('cancelled', 'Отменён')], default='draft', max_length=20, verbose_name='статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts_created', to=settings.AUTH_USER_MODEL, verbose_name='оформил')),
            ],
            options={
                'verbose_name': 'поступление',
                'verbose_name_plural': 'поступления',
                'ordering': ('-receipt_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='количество')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='цена за ед.')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='сумма строки')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='SKLAD.product', verbose_name='товар')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='SKLAD.receipt', verbose_name='поступление')),
            ],
            options={
                'verbose_name': 'позиция поступления',
                'verbose_name_plural': 'позиции поступлений',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Writeoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=64, unique=True, verbose_name='номер документа')),
                ('writeoff_date', models.DateField(verbose_name='дата списания')),
                ('reason', models.TextField(verbose_name='причина')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('posted', 'Проведён'), ('cancelled', 'Отменён')], default='draft', max_length=20, verbose_name='статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='writeoffs_created', to=settings.AUTH_USER_MODEL, verbose_name='оформил')),
            ],
            options={
                'verbose_name': 'списание',
                'verbose_name_plural': 'списания',
                'ordering': ('-writeoff_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='WriteoffLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='количество')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='цена за ед.')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='сумма строки')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='writeoff_lines', to='SKLAD.product', verbose_name='товар')),
                ('writeoff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='SKLAD.writeoff', verbose_name='списание')),
            ],
            options={
                'verbose_name': 'позиция списания',
                'verbose_name_plural': 'позиции списаний',
                'ordering': ('id',),
            },
        ),
    ]
